os: Visual Studio 2015

platform:
    - x64
    - x86

environment:
    global:
        UNRAR_INCLUDE: sw/include
        UNRAR_LIBDIRS: sw/lib

build_script:
    - ps: |
        If ($env:Platform -Match "x86") {
            $env:VCVARS_PLATFORM="x86"
            $env:PATH="C:/Python36;$env:PATH"
        } Else {
            $env:VCVARS_PLATFORM="amd64"
            $env:PATH="C:/Python36-x64;$env:PATH"
        }
    - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%
    - python.exe -c "import sys; print(sys.version_info); import platform; print(platform.architecture())"
    - python.exe ci.py

test_script:
    - python.exe setup.py test
