dist: trusty
sudo: false

env:
    global:
        - PYTHONHASHSEED=random
        - UNRAR_INCLUDE=sw/include
        - UNRAR_LIBDIRS=sw/lib
        - LD_LIBRARY_PATH=sw/lib
        - DYLD_LIBRARY_PATH=sw/lib

matrix:
    include:
        - os: linux
          language: python
          python: 2.7
        - os: linux
          language: python
          python: 3.4

        - os: osx
          python:
          language: generic

install:
    - pip install psutil
    - python ci.py

script:
    - python setup.py test
